//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoonLearning.AppCenter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoonLearning.AppCenter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Gadget Center v{0}..
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Apps.
        /// </summary>
        public static string AllApps {
            get {
                return ResourceManager.GetString("AllApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AppCenterDescription {
            get {
                return ResourceManager.GetString("AppCenterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color:.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image:.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to back to the gadget list?
        ///If you back to the gadget list the current operation will be lost..
        /// </summary>
        public static string BackWarning {
            get {
                return ResourceManager.GetString("BackWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautiful Flower.
        /// </summary>
        public static string BeautifulFlower {
            get {
                return ResourceManager.GetString("BeautifulFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Sky.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Fail.
        /// </summary>
        public static string DownloadFail {
            get {
                return ResourceManager.GetString("DownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some gadgets support speech recognizer. Enable speech recognizer now!.
        /// </summary>
        public static string EnableSpeechRecognizer {
            get {
                return ResourceManager.GetString("EnableSpeechRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Color.
        /// </summary>
        public static string EndColor {
            get {
                return ResourceManager.GetString("EndColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have passed this stage. Enter next stage or retry this stage?.
        /// </summary>
        public static string EnterNextStage {
            get {
                return ResourceManager.GetString("EnterNextStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between min value and max value..
        /// </summary>
        public static string EnterValueBetweenMinAndMax {
            get {
                return ResourceManager.GetString("EnterValueBetweenMinAndMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Color:.
        /// </summary>
        public static string ForegroundColor {
            get {
                return ResourceManager.GetString("ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen Apps.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Leaf.
        /// </summary>
        public static string GreenLeaf {
            get {
                return ResourceManager.GetString("GreenLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal characters or {0}.
        /// </summary>
        public static string IllegalCharacters {
            get {
                return ResourceManager.GetString("IllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Apps.
        /// </summary>
        public static string InstalledApps {
            get {
                return ResourceManager.GetString("InstalledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Fail.
        /// </summary>
        public static string InstallFail {
            get {
                return ResourceManager.GetString("InstallFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Time:.
        /// </summary>
        public static string LeftTime {
            get {
                return ResourceManager.GetString("LeftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Done， {0} gadgets have been loaded..
        /// </summary>
        public static string LoadingDone {
            get {
                return ResourceManager.GetString("LoadingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadget Center is loading data..
        /// </summary>
        public static string LoadingGadgetData {
            get {
                return ResourceManager.GetString("LoadingGadgetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadiing {0}， {1}.
        /// </summary>
        public static string LoadingIndex {
            get {
                return ResourceManager.GetString("LoadingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading online apps information... ....
        /// </summary>
        public static string LoadOnlineGadgetInfo {
            get {
                return ResourceManager.GetString("LoadOnlineGadgetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Apps.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.
        /// </summary>
        public static string Math {
            get {
                return ResourceManager.GetString("Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematics Basic.
        /// </summary>
        public static string Math_Basic {
            get {
                return ResourceManager.GetString("Math_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematic Game.
        /// </summary>
        public static string Math_Game {
            get {
                return ResourceManager.GetString("Math_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematics Olympic.
        /// </summary>
        public static string Math_Olympic {
            get {
                return ResourceManager.GetString("Math_Olympic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid.
        /// </summary>
        public static string Math_Rapid {
            get {
                return ResourceManager.GetString("Math_Rapid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular.
        /// </summary>
        public static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Stage.
        /// </summary>
        public static string NextStage {
            get {
                return ResourceManager.GetString("NextStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I still need you!.
        /// </summary>
        public static string NotExit {
            get {
                return ResourceManager.GetString("NotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Pass.
        /// </summary>
        public static string NotPass {
            get {
                return ResourceManager.GetString("NotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        public static string NotStart {
            get {
                return ResourceManager.GetString("NotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sound.
        /// </summary>
        public static string OpenSound {
            get {
                return ResourceManager.GetString("OpenSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        public static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Stage.
        /// </summary>
        public static string PreStage {
            get {
                return ResourceManager.GetString("PreStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle.
        /// </summary>
        public static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Puzzle.
        /// </summary>
        public static string Puzzle_Block {
            get {
                return ResourceManager.GetString("Puzzle_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jigsaw Puzzle.
        /// </summary>
        public static string Puzzle_Jigsaw {
            get {
                return ResourceManager.GetString("Puzzle_Jigsaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Puzzle.
        /// </summary>
        public static string Puzzle_Other {
            get {
                return ResourceManager.GetString("Puzzle_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Update.
        /// </summary>
        public static string RecentUpdate {
            get {
                return ResourceManager.GetString("RecentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You fail to pass this stage. Try this stage again..
        /// </summary>
        public static string RetryStage {
            get {
                return ResourceManager.GetString("RetryStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a gadget from the gadget list!.
        /// </summary>
        public static string SelectGadgetTip {
            get {
                return ResourceManager.GetString("SelectGadgetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognizer.
        /// </summary>
        public static string SpeechRecognizer {
            get {
                return ResourceManager.GetString("SpeechRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage List.
        /// </summary>
        public static string StageList {
            get {
                return ResourceManager.GetString("StageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Color.
        /// </summary>
        public static string StartColor {
            get {
                return ResourceManager.GetString("StartColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to Use.
        /// </summary>
        public static string StartToUse {
            get {
                return ResourceManager.GetString("StartToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soon Learning Intelligent System.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Style:.
        /// </summary>
        public static string UIStyle {
            get {
                return ResourceManager.GetString("UIStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string UserCancelled {
            get {
                return ResourceManager.GetString("UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string UserCancelling {
            get {
                return ResourceManager.GetString("UserCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Installing List.
        /// </summary>
        public static string ViewInstallingList {
            get {
                return ResourceManager.GetString("ViewInstallingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string WarningExit {
            get {
                return ResourceManager.GetString("WarningExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Bye Gadget Center..
        /// </summary>
        public static string YesExit {
            get {
                return ResourceManager.GetString("YesExit", resourceCulture);
            }
        }
    }
}
