//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoonLearning.BlockPuzzle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoonLearning.BlockPuzzle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator:.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Best Answer.
        /// </summary>
        public static string getAnswer {
            get {
                return ResourceManager.GetString("getAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume the picture by click the different rectangle..
        /// </summary>
        public static string GoalText {
            get {
                return ResourceManager.GetString("GoalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to go back to the puzzle list?.
        /// </summary>
        public static string GoBackWarning {
            get {
                return ResourceManager.GetString("GoBackWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image:.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.bmp;*.png;*.jpeg|All Files|*.*.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix Up.
        /// </summary>
        public static string mixUp {
            get {
                return ResourceManager.GetString("mixUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have move {0} steps!.
        /// </summary>
        public static string movedStepCount {
            get {
                return ResourceManager.GetString("movedStepCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Puzzle.
        /// </summary>
        public static string NewPuzzle {
            get {
                return ResourceManager.GetString("NewPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string nextStep {
            get {
                return ResourceManager.GetString("nextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the different rectangle by click mouse left button. Only the rectangle which has blank rectangle next to it can be moved..
        /// </summary>
        public static string OperationText {
            get {
                return ResourceManager.GetString("OperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Step.
        /// </summary>
        public static string preStep {
            get {
                return ResourceManager.GetString("preStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 2 x 2 Puzzle.
        /// </summary>
        public static string puzzle2x2Description {
            get {
                return ResourceManager.GetString("puzzle2x2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 x 2 Puzzle.
        /// </summary>
        public static string puzzle2x2Title {
            get {
                return ResourceManager.GetString("puzzle2x2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 x 3 Puzzle is a puzzule which will split a picture into 2 columes and 3 rows.
        /// </summary>
        public static string puzzle2x3Description {
            get {
                return ResourceManager.GetString("puzzle2x3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 x 3 Puzzle.
        /// </summary>
        public static string puzzle2x3Title {
            get {
                return ResourceManager.GetString("puzzle2x3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 3 x 2 Puzzle.
        /// </summary>
        public static string puzzle3x2Description {
            get {
                return ResourceManager.GetString("puzzle3x2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 x 2 Puzzle.
        /// </summary>
        public static string puzzle3x2Title {
            get {
                return ResourceManager.GetString("puzzle3x2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 3 x 3 Puzzle.
        /// </summary>
        public static string puzzle3x3Description {
            get {
                return ResourceManager.GetString("puzzle3x3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 x 3 Puzzle.
        /// </summary>
        public static string puzzle3x3Title {
            get {
                return ResourceManager.GetString("puzzle3x3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle List.
        /// </summary>
        public static string PuzzleList {
            get {
                return ResourceManager.GetString("PuzzleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can recognize the different part of the picture..
        /// </summary>
        public static string RequestText {
            get {
                return ResourceManager.GetString("RequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image file for the new puzzle..
        /// </summary>
        public static string SelectImageForNewPuzzle {
            get {
                return ResourceManager.GetString("SelectImageForNewPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Numbers.
        /// </summary>
        public static string showNumbers {
            get {
                return ResourceManager.GetString("showNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Steps of {1}.
        /// </summary>
        public static string StepsOfTotal {
            get {
                return ResourceManager.GetString("StepsOfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of new puzzle cannot be empty..
        /// </summary>
        public static string TitleEmpty {
            get {
                return ResourceManager.GetString("TitleEmpty", resourceCulture);
            }
        }
    }
}
