//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoonLearning.Assessment.Player.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoonLearning.Assessment.Player.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;宋体&quot;
        ///              Foreground=&quot;Black&quot;&gt;
        ///    &lt;Paragraph TextAlignment=&quot;Center&quot;&gt;
        ///        &lt;Run FontSize=&quot;36&quot;
        ///             FontWeight=&quot;Medium&quot; 
        ///             Foreground=&quot;Black&quot;&gt;_$PAPER_TITLE$_&lt;/Run&gt;
        ///    &lt;/Paragraph&gt;
        ///    
        ///    &lt;Paragraph TextAlignment=&quot;Center&quot;&gt;
        ///        &lt;Run FontSize=&quot;28&quot;
        ///             FontWeight=&quot;Normal&quot;
        ///             Foreground=&quot;Black&quot;&gt;_$PAPER_DESPRITON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuestionPaperDocument {
            get {
                return ResourceManager.GetString("QuestionPaperDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  列.
        /// </summary>
        internal static string strColumn {
            get {
                return ResourceManager.GetString("strColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行.
        /// </summary>
        internal static string strLine {
            get {
                return ResourceManager.GetString("strLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑HTML模板.
        /// </summary>
        internal static string txtEditation {
            get {
                return ResourceManager.GetString("txtEditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑模板.
        /// </summary>
        internal static string txtEditorName {
            get {
                return ResourceManager.GetString("txtEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入文件名.
        /// </summary>
        internal static string txtEnterFileName {
            get {
                return ResourceManager.GetString("txtEnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入图片路劲.
        /// </summary>
        internal static string txtEnterPicturePath {
            get {
                return ResourceManager.GetString("txtEnterPicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件失败.
        /// </summary>
        internal static string txtLoadFailed {
            get {
                return ResourceManager.GetString("txtLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入链接失败.
        /// </summary>
        internal static string txtLoadHyperlinkFailed {
            get {
                return ResourceManager.GetString("txtLoadHyperlinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入图片失败.
        /// </summary>
        internal static string txtLoadPictureFailed {
            get {
                return ResourceManager.GetString("txtLoadPictureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片无效.
        /// </summary>
        internal static string txtNotValidPictureAddress {
            get {
                return ResourceManager.GetString("txtNotValidPictureAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持该图片文件格式，你确定要插入到文档中吗？.
        /// </summary>
        internal static string txtNotValidPictureType {
            get {
                return ResourceManager.GetString("txtNotValidPictureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url地址无效.
        /// </summary>
        internal static string txtNotValidUrlAddress {
            get {
                return ResourceManager.GetString("txtNotValidUrlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件失败.
        /// </summary>
        internal static string txtOpenFileFailed {
            get {
                return ResourceManager.GetString("txtOpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        internal static string txtPicture {
            get {
                return ResourceManager.GetString("txtPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片文件 (*.bmp, *.jpg, *.gif)|*.bmp;*.jpg;*.gif.
        /// </summary>
        internal static string txtPictures {
            get {
                return ResourceManager.GetString("txtPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印失败.
        /// </summary>
        internal static string txtPrintFailed {
            get {
                return ResourceManager.GetString("txtPrintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性.
        /// </summary>
        internal static string txtProperties {
            get {
                return ResourceManager.GetString("txtProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件 (*.htm, *.html, *.xml, *.fdc, *.xaml, *.rtf)|*.htm;*.html;*.xml;*.fdc;*.xaml;*.rtf.
        /// </summary>
        internal static string txtSupportedDocuments {
            get {
                return ResourceManager.GetString("txtSupportedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格.
        /// </summary>
        internal static string txtTable {
            get {
                return ResourceManager.GetString("txtTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACM - 打印模板.
        /// </summary>
        internal static string txtTemplatePrintDesc {
            get {
                return ResourceManager.GetString("txtTemplatePrintDesc", resourceCulture);
            }
        }
    }
}
