//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoonLearning.Math.Fast.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoonLearning.Math.Fast.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct: {0}.
        /// </summary>
        public static string Corrrent {
            get {
                return ResourceManager.GetString("Corrrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to finish this test?.
        /// </summary>
        public static string FinishTestWarning {
            get {
                return ResourceManager.GetString("FinishTestWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating {0} / {1}.
        /// </summary>
        public static string generatingQuestion {
            get {
                return ResourceManager.GetString("generatingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect: {0}.
        /// </summary>
        public static string InCorrect {
            get {
                return ResourceManager.GetString("InCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Time:.
        /// </summary>
        public static string LeftTime {
            get {
                return ResourceManager.GetString("LeftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指利用数与数之间的特殊关系进行较快的加减乘除运算。这种运算方法称为速算法，心算法。.
        /// </summary>
        public static string mathAddMinusDescription {
            get {
                return ResourceManager.GetString("mathAddMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid calculation (+/-/x//).
        /// </summary>
        public static string mathAddMinusMultiplyDivisionTitle {
            get {
                return ResourceManager.GetString("mathAddMinusMultiplyDivisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid calculation (+/-).
        /// </summary>
        public static string mathAddMinusTitle {
            get {
                return ResourceManager.GetString("mathAddMinusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在规定的时间内快速的完成一定数量的加减乘除运算。.
        /// </summary>
        public static string mathAMMDDescription {
            get {
                return ResourceManager.GetString("mathAMMDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在规定的时间内快速的完成一定数量的乘除运算。.
        /// </summary>
        public static string mathMDDescription {
            get {
                return ResourceManager.GetString("mathMDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid calculation (x//).
        /// </summary>
        public static string mathMultiplyDivisionTitle {
            get {
                return ResourceManager.GetString("mathMultiplyDivisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create a new quiz?.
        /// </summary>
        public static string NewQuizWarning {
            get {
                return ResourceManager.GetString("NewQuizWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Test.
        /// </summary>
        public static string NewTest {
            get {
                return ResourceManager.GetString("NewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 x 9 Table.
        /// </summary>
        public static string NineXNineTableDescription {
            get {
                return ResourceManager.GetString("NineXNineTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 x 9 Table.
        /// </summary>
        public static string NineXNineTableTitle {
            get {
                return ResourceManager.GetString("NineXNineTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Answer: {0}.
        /// </summary>
        public static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Pass.
        /// </summary>
        public static string NotPass {
            get {
                return ResourceManager.GetString("NotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sound.
        /// </summary>
        public static string OpenSound {
            get {
                return ResourceManager.GetString("OpenSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Virtual Keyboard.
        /// </summary>
        public static string OpenVirtualKeyboard {
            get {
                return ResourceManager.GetString("OpenVirtualKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page: {0} / Total Page: {1}.
        /// </summary>
        public static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        public static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} questions per page.
        /// </summary>
        public static string questionCountPerPage {
            get {
                return ResourceManager.GetString("questionCountPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Data File(*.qdf)|*.qdf.
        /// </summary>
        public static string QuestionDataFilter {
            get {
                return ResourceManager.GetString("QuestionDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some questions have not been answered. Are you sure you want to finish this test?.
        /// </summary>
        public static string QuestionNotAnswered {
            get {
                return ResourceManager.GetString("QuestionNotAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;16&quot; FontFamily=&quot;宋体&quot;
        ///              Foreground=&quot;Black&quot;&gt;
        ///    &lt;Paragraph TextAlignment=&quot;Center&quot;&gt;
        ///        &lt;Run FontSize=&quot;36&quot;
        ///             FontWeight=&quot;Medium&quot; 
        ///             Foreground=&quot;Black&quot;&gt;_$PAPER_TITLE$_&lt;/Run&gt;
        ///    &lt;/Paragraph&gt;
        ///    
        ///    &lt;Paragraph TextAlignment=&quot;Center&quot;&gt;
        ///        &lt;Run FontSize=&quot;28&quot;
        ///             FontWeight=&quot;Normal&quot;
        ///             Foreground=&quot;Black&quot;&gt;_$PAPER_DESPRITON [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QuestionPaperDocument {
            get {
                return ResourceManager.GetString("QuestionPaperDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quiz time is out. you cannot anwser any queston now..
        /// </summary>
        public static string QuizTimeOut {
            get {
                return ResourceManager.GetString("QuizTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to save question data. 
        ///Exception: {0}.
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:{0}.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Test.
        /// </summary>
        public static string ViewResult {
            get {
                return ResourceManager.GetString("ViewResult", resourceCulture);
            }
        }
    }
}
